# USO DE SEMANTIC RELASE
# Este workflow genera versiones y releases a demanda.
# Se recomienda utilizar un archivo .github/release.yml para configurar el CHANGELOG.
# ver examples/release-config.yml
#
# Copia este archivo a: .github/workflows/release.yml en tu repositorio.

name: Release Pipeline

on:
  workflow_dispatch: # <- Boton manual en GitHub

permissions:
    contents: write

jobs:
  call-release:
    name: Call Shared Release
    uses: lyoss-usm/workflows/.github/workflows/semantic-release.yml@main
    secrets: inherit # Esto usa los secretos del repo o de la organizacion. (GH_PAT es requerido)
